### ISSUE TITLE
Convert Text Files to Markdown

### ISSUE THREAD

**Issue by jrtechs** [PerryXDeng/data_science_resources#1]
Renaming your text files as markdown files will help other people use this repository. Github gives nice displays for markdown files. You can even write issues in Markdown!

# Header
these are nice

## Sub headers
also cool

- lists
- are
- cool

[links easy to create](https://jrtechs.net)

**Comment by PerryXDeng** [comment]
Thank you for the valuable suggestion. The issue has been resolved with backward formatting compatibility through a .txt - .md compiling script.
